### ISSUE TITLE
Upgrading from 1.4.0 to 1.4.1 failing

### ISSUE THREAD

**Issue by ldemattos** [bakoontz/WikkaWiki#1305]
Hello,

I am trying to upgrade from Wikka 1.4.0 to its newest 1.4.1 version and the web updater is throwing back at me:

> Testing Configuration
> Testing DB connection settings... OK
> 
> 
> Checking availability of default pages... OK
> 1.4.0 to 1.4.1 changes:
> mysqlAdding/Updating default page WikkaInstaller... OK
> PDOException: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'signuptime' in /var/www/wiki.mattos.eng.br/setup/inc/functions.inc.php:78 Stack trace: #0 /var/www/wiki.mattos.eng.br/setup/inc/functions.inc.php(78): PDOStatement->execute(NULL) #1 /var/www/wiki.mattos.eng.br/setup/inc/db_update_mysql.php(545): db_query('ALTER TABLE wik...', NULL, Object(PDO)) #2 /var/www/wiki.mattos.eng.br/setup/install.php(89): require('/var/www/wiki.m...') #3 /var/www/wiki.mattos.eng.br/wikka.php(648): include('/var/www/wiki.m...') #4 {main}Altering users table structure (default_comment_display)... FAILED
> 
> Failed. ?

Any ideas how to overcome this error?

Thanks in advance!

**Comment by bakoontz** [comment]
I believe this issue is related to MySQL's abrupt deprecation of default date fields with the 5.2 release.  It's related to #1294.  Most likely, if you look at your wikka_users table (mysql> describe wikka_users) you'll see that the default value for the "signuptime" field is something like "0000-00-00".  This is no longer a valid date default in MySQL versions >= 5.2.

The quick fix is to run something like this:

```
mysql> use my_wikka_database;
mysql> update wikka_users set signuptime='1900-01-01 00:00:00' where signuptime=convert(0,datetime);
```
then re-run the update.

**Comment by bakoontz** [comment]
Nothing hear in 2 months; closing.

**Comment by bakoontz** [comment]
No response in 2 months; closing.
